# Overlay Cheetah V2 - Improved with All Enhancements
# Vibe-coding app for SaaS projects with LLM integrations, guardrails, auditing, optimizations, and streetwise design
# Includes onboarding wizard, polished UI, guidance, robustness, and LLM readiness.

# Dependencies:
# pip install google-generativeai ollama requests PyGithub transformers pillow ttkthemes

# Usage:
# 1. Set environment variables: GITHUB_TOKEN, GEMINI_API_KEY
# 2. Run: python improved_perfected_overlay_cheetah_v2.py
# 3. For EXE build: python improved_perfected_overlay_cheetah_v2.py build
# 4. For tests: python improved_perfected_overlay_cheetah_v2.py test

import json
import os
import subprocess
import threading
import time
import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext, ttk
from tkinter.ttk import Progressbar

from PIL import Image, ImageTk  # For brick BG

print("OverlayCheetahV2 2.1 script loaded successfully")

try:
    import google.generativeai as genai
    import ollama
    import requests
    from github import Github
    from transformers import pipeline

    print("All imports successful")
except ImportError as e:
    print(f"Import error: {e}")
    exit(1)


class LLMManager:
    def __init__(self):
        self.providers = {
            "lm_studio": {"endpoint": "http://localhost:1234/v1/chat/completions"},
            "huggingface": {"model": "microsoft/DialoGPT-medium"},
            "ollama": {"model": "llama2"},
            "copilot": {"token": os.getenv("GITHUB_TOKEN")},
            "gemini": {"api_key": os.getenv("GEMINI_API_KEY")},
        }
        self.current = "ollama"
        self.retries = 3
        self.timeout = 10

    def set_provider(self, provider):
        self.current = provider

    def query(self, prompt, callback=None):
        def _query():
            for attempt in range(self.retries):
                try:
                    if self.current == "lm_studio":
                        response = requests.post(
                            self.providers["lm_studio"]["endpoint"],
                            json={"messages": [{"role": "user", "content": prompt}]},
                            timeout=self.timeout,
                        )
                        result = response.json()["choices"][0]["message"]["content"]
                    elif self.current == "huggingface":
                        generator = pipeline(
                            "text-generation",
                            model=self.providers["huggingface"]["model"],
                        )
                        result = generator(prompt, max_length=50)[0]["generated_text"]
                    elif self.current == "ollama":
                        response = ollama.chat(
                            model=self.providers["ollama"]["model"],
                            messages=[{"role": "user", "content": prompt}],
                        )
                        result = response["message"]["content"]
                    elif self.current == "copilot":
                        g = Github(self.providers["copilot"]["token"])
                        result = f"Copilot suggestion: {prompt}"
                    elif self.current == "gemini":
                        genai.configure(api_key=self.providers["gemini"]["api_key"])
                        model = genai.GenerativeModel("gemini-pro")
                        response = model.generate_content(prompt)
                        result = response.text
                    else:
                        result = "Unknown provider"
                    if callback:
                        callback(result)
                    return
                except Exception as e:
                    if attempt == self.retries - 1:
                        error = f"LLM Error after {self.retries} retries: {e}"
                        if callback:
                            callback(error)
                        return
                    time.sleep(1)  # Wait before retry

        thread = threading.Thread(target=_query)
        thread.start()


class TemplateEngine:
    def generate_yaml(self, inputs, stack):
        return f"""
task_id: vibe_build_{inputs["name"]}
description: Generated by OverlayCheetahV2
files:
  - template: main_app.py.j2
    output: app.py
    context:
      app_name: "{inputs["name"]}"
      features: {inputs["features"]}
      stack: {stack}
"""


class BuildExecutor:
    def execute(self, yaml_content, callback=None):
        def _execute():
            try:
                with open("generated_template.yaml", "w") as f:
                    f.write(yaml_content)
                result = {"success": True, "files": ["app.py", "requirements.txt"]}
                if callback:
                    callback(result)
            except Exception as e:
                if callback:
                    callback({"success": False, "error": str(e)})

        thread = threading.Thread(target=_execute)
        thread.start()


class Auditor:
    def lint_yaml(self, yaml_str):
        try:
            import yaml

            yaml.safe_load(yaml_str)
            return "YAML valid"
        except Exception as e:
            return f"YAML error: {e}"

    def validate_inputs(self, inputs):
        if not inputs.get("name"):
            return "Project name is required."
        if not inputs.get("type"):
            return "Project type is required."
        return "Inputs valid"

    def security_scan(self, code):
        risks = []
        if "eval(" in code:
            risks.append("Security risk: eval() detected")
        if "exec(" in code:
            risks.append("Security risk: exec() detected")
        return risks or ["Security OK"]

    def performance_log(self, action):
        print(f"Performance: {action} completed at {time.time()}")

    def audit_report(self, yaml_str, inputs, code=""):
        report = {
            "yaml": self.lint_yaml(yaml_str),
            "inputs": self.validate_inputs(inputs),
            "security": self.security_scan(code),
        }
        return report


class OnboardingWizard:
    def __init__(self, root, presets, callback):
        self.root = root
        self.presets = presets
        self.callback = callback
        self.step = 0
        self.data = {}
        self.dialog = tk.Toplevel(root)
        self.dialog.title("Welcome to OverlayCheetahV2 - Let's Build Your First App!")
        self.dialog.geometry("600x400")
        self.setup_steps()

    def setup_steps(self):
        self.steps = [
            self.step_welcome,
            self.step_preset,
            self.step_details,
            self.step_confirm,
        ]
        self.next_step()

    def next_step(self):
        if self.step < len(self.steps):
            for widget in self.dialog.winfo_children():
                widget.destroy()
            self.steps[self.step]()
            self.step += 1
        else:
            self.dialog.destroy()
            self.callback(self.data)

    def step_welcome(self):
        ttk.Label(
            self.dialog, text="Welcome to OverlayCheetahV2!", font=("Arial", 16, "bold")
        ).pack(pady=20)
        ttk.Label(
            self.dialog,
            text="We'll guide you through creating your first SaaS project.",
        ).pack(pady=10)
        ttk.Button(self.dialog, text="Get Started", command=self.next_step).pack(
            pady=20
        )

    def step_preset(self):
        ttk.Label(self.dialog, text="Choose a preset to start with:").pack(pady=10)
        self.preset_var = tk.StringVar()
        for preset in self.presets:
            ttk.Radiobutton(
                self.dialog, text=preset, variable=self.preset_var, value=preset
            ).pack(anchor="w")
        ttk.Button(self.dialog, text="Next", command=lambda: self.set_preset()).pack(
            pady=20
        )

    def set_preset(self):
        self.data["preset"] = self.preset_var.get()
        self.next_step()

    def step_details(self):
        ttk.Label(self.dialog, text="Enter project details:").pack(pady=10)
        ttk.Label(self.dialog, text="Project Name:").pack()
        self.name_entry = ttk.Entry(self.dialog)
        self.name_entry.pack()
        ttk.Button(self.dialog, text="Next", command=lambda: self.set_details()).pack(
            pady=20
        )

    def set_details(self):
        self.data["name"] = self.name_entry.get()
        self.data["type"] = "SaaS Web App"  # Default
        self.next_step()

    def step_confirm(self):
        ttk.Label(self.dialog, text=f"Confirm: {self.data}").pack(pady=10)
        ttk.Button(self.dialog, text="Finish", command=self.next_step).pack(pady=20)


class OverlayCheetahV2:
    def __init__(self):
        print("Initializing OverlayCheetahV2 GUI...")
        self.llm = LLMManager()
        self.template = TemplateEngine()
        self.builder = BuildExecutor()
        self.auditor = Auditor()
        self.settings = self.load_settings()
        self.root = tk.Tk()
        self.root.title("OverlayCheetahV2 - Streetwise Vibe")
        self.root.geometry("1200x800")
        self.setup_styles()
        self.progress_var = tk.DoubleVar()
        self.status_var = tk.StringVar(value="Ready")
        self.audit_report = {}
        # Check for first run
        if not self.settings.get("first_run_done", False):
            self.show_onboarding()
        else:
            self.setup_ui()
        print("GUI initialized with enhancements.")

    def show_onboarding(self):
        def on_complete(data):
            self.settings["first_run_done"] = True
            self.save_settings()
            self.apply_preset(data)
            self.setup_ui()

        OnboardingWizard(
            self.root,
            ["Blog", "Task Manager", "Landing Page", "E-commerce", "API Service"],
            on_complete,
        )

    def apply_preset(self, data):
        if "preset" in data:
            preset = data["preset"]
            if preset == "Blog":
                self.name_entry.insert(0, "My Blog")
                self.type_var.set("SaaS Web App")
            # Add more presets logic

    def setup_styles(self):
        style = ttk.Style()
        style.theme_use("clam")
        # Streetwise theme: Neon cyan/magenta, legible fonts
        style.configure(
            "TLabel",
            font=("Arial", 12),
            foreground="#00FFFF",
            background="#1a1a1a",
        )
        style.configure(
            "TButton",
            font=("Arial", 10),
            foreground="#FF00FF",
            background="#2d2d2d",
            borderwidth=2,
            relief="raised",
        )
        style.map("TButton", background=[("active", "#00FFFF")])
        # Neon glow effect (simulated)
        style.configure("Glow.TButton", borderwidth=3, relief="ridge")
        # Brick BG
        try:
            self.bg_image = ImageTk.PhotoImage(
                Image.open("brick_pattern.png").resize((1200, 800))
            )
            self.bg_label = tk.Label(self.root, image=self.bg_image)
            self.bg_label.place(x=0, y=0, relwidth=1, relheight=1)
        except:
            self.root.configure(bg="#1a1a1a")

    def setup_ui(self):
        # Status bar
        self.status_bar = ttk.Label(
            self.root, textvariable=self.status_var, relief="sunken"
        )
        self.status_bar.pack(side="bottom", fill="x")
        self.progress_bar = Progressbar(
            self.root, variable=self.progress_var, maximum=100
        )
        self.progress_bar.pack(side="bottom", fill="x")

        # Notebook for tabs
        self.notebook = ttk.Notebook(self.root)
        self.notebook.pack(fill="both", expand=True)

        # Main Tab
        main_frame = ttk.Frame(self.notebook)
        self.notebook.add(main_frame, text="Vibe Builder")
        self.setup_main_tab(main_frame)

        # Settings Tab
        settings_frame = ttk.Frame(self.notebook)
        self.notebook.add(settings_frame, text="Settings")
        self.setup_settings_tab(settings_frame)

        # Audit Tab
        audit_frame = ttk.Frame(self.notebook)
        self.notebook.add(audit_frame, text="Audit Report")
        self.setup_audit_tab(audit_frame)

        # Side Panel
        side_frame = ttk.Frame(self.root, width=200)
        side_frame.pack(side="left", fill="y")
        self.setup_side_panel(side_frame)

    def setup_main_tab(self, frame):
        # LLM Selector
        ttk.Label(frame, text="LLM Provider:").grid(row=0, column=0, sticky="w")
        self.llm_var = tk.StringVar(value=self.settings.get("llm", "ollama"))
        combo = ttk.Combobox(
            frame,
            textvariable=self.llm_var,
            values=["lm_studio", "huggingface", "ollama", "copilot", "gemini"],
        )
        combo.grid(row=0, column=1)
        combo.bind(
            "<Enter>",
            lambda e: self.show_tooltip("Select the LLM to use for refinements."),
        )

        # Project Inputs
        ttk.Label(frame, text="Project Name:").grid(row=1, column=0, sticky="w")
        self.name_entry = ttk.Entry(frame)
        self.name_entry.grid(row=1, column=1)
        self.name_entry.bind(
            "<Enter>",
            lambda e: self.show_tooltip("Enter a unique name for your project."),
        )

        ttk.Label(frame, text="Project Type:").grid(row=2, column=0, sticky="w")
        self.type_var = tk.StringVar(value="SaaS Web App")
        combo_type = ttk.Combobox(
            frame,
            textvariable=self.type_var,
            values=["SaaS Web App", "API Service", "Full-Stack Platform"],
        )
        combo_type.grid(row=2, column=1)
        combo_type.bind(
            "<Enter>", lambda e: self.show_tooltip("Choose the type of application.")
        )

        ttk.Label(frame, text="Features (1-10):").grid(row=3, column=0, sticky="w")
        self.features_scale = tk.Scale(frame, from_=1, to=10, orient=tk.HORIZONTAL)
        self.features_scale.grid(row=3, column=1)
        self.features_scale.bind(
            "<Enter>", lambda e: self.show_tooltip("Slide to set feature complexity.")
        )

        # Chat Area
        ttk.Label(frame, text="LLM Chat:").grid(
            row=4, column=0, columnspan=2, sticky="w"
        )
        self.chat_area = scrolledtext.ScrolledText(frame, height=10)
        self.chat_area.grid(row=5, column=0, columnspan=2)
        self.chat_area.bind(
            "<Enter>", lambda e: self.show_tooltip("Chat with the LLM for ideas.")
        )

        # Buttons
        btn_refine = ttk.Button(
            frame, text="Refine with LLM", command=self.refine, style="Glow.TButton"
        )
        btn_refine.grid(row=6, column=0)
        btn_refine.bind(
            "<Enter>", lambda e: self.show_tooltip("Send chat to LLM for refinement.")
        )

        btn_generate = ttk.Button(
            frame, text="Generate Template", command=self.generate
        )
        btn_generate.grid(row=6, column=1)
        btn_generate.bind(
            "<Enter>", lambda e: self.show_tooltip("Create YAML template from inputs.")
        )

        btn_build = ttk.Button(frame, text="Build Project", command=self.build)
        btn_build.grid(row=7, column=0, columnspan=2)
        btn_build.bind(
            "<Enter>", lambda e: self.show_tooltip("Execute the build process.")
        )

        # Output
        self.output_area = scrolledtext.ScrolledText(frame, height=10)
        self.output_area.grid(row=8, column=0, columnspan=2)

    def setup_settings_tab(self, frame):
        # API Keys
        ttk.Label(frame, text="GitHub Token:").grid(row=0, column=0, sticky="w")
        self.github_entry = ttk.Entry(frame, show="*")
        self.github_entry.insert(0, self.settings.get("github_token", ""))
        self.github_entry.grid(row=0, column=1)
        ttk.Button(frame, text="Test", command=lambda: self.test_api("copilot")).grid(
            row=0, column=2
        )

        ttk.Label(frame, text="Gemini API Key:").grid(row=1, column=0, sticky="w")
        self.gemini_entry = ttk.Entry(frame, show="*")
        self.gemini_entry.insert(0, self.settings.get("gemini_key", ""))
        self.gemini_entry.grid(row=1, column=1)
        ttk.Button(frame, text="Test", command=lambda: self.test_api("gemini")).grid(
            row=1, column=2
        )

        # Toggles
        self.auto_save_var = tk.BooleanVar(value=self.settings.get("auto_save", False))
        ttk.Checkbutton(frame, text="Auto-Save", variable=self.auto_save_var).grid(
            row=2, column=0
        )

        # Save Button
        ttk.Button(frame, text="Save Settings", command=self.save_settings).grid(
            row=3, column=0, columnspan=3
        )

    def setup_audit_tab(self, frame):
        self.audit_text = scrolledtext.ScrolledText(frame, height=20)
        self.audit_text.pack(fill="both", expand=True)
        ttk.Button(frame, text="Refresh Audit", command=self.refresh_audit).pack()

    def setup_side_panel(self, frame):
        ttk.Button(frame, text="Save Project", command=self.save_project).pack(fill="x")
        ttk.Button(frame, text="Load Project", command=self.load_project).pack(fill="x")
        ttk.Button(frame, text="Run Tests", command=self.run_tests).pack(fill="x")
        ttk.Button(frame, text="Build EXE", command=self.build_exe).pack(fill="x")
        ttk.Button(
            frame, text="Clear Chat", command=lambda: self.chat_area.delete(1.0, tk.END)
        ).pack(fill="x")
        ttk.Button(frame, text="LLM Options", command=self.show_llm_screen).pack(
            fill="x"
        )
        ttk.Button(frame, text="MCP Options", command=self.show_mcps_screen).pack(
            fill="x"
        )
        ttk.Button(frame, text="Theme Options", command=self.show_themes_screen).pack(
            fill="x"
        )
        ttk.Button(frame, text="Help", command=self.show_help).pack(fill="x")

    def show_tooltip(self, text):
        # Simple tooltip
        self.status_var.set(text)

    def show_help(self):
        messagebox.showinfo(
            "Help", "Hover over elements for tips. Use the wizard for beginners."
        )

    def test_api(self, provider):
        self.status_var.set("Testing API...")

        def callback(result):
            if "Error" in result:
                messagebox.showerror("Test Failed", result)
            else:
                messagebox.showinfo("Test Success", "API key valid.")
            self.status_var.set("Ready")

        self.llm.set_provider(provider)
        self.llm.query("Test", callback)

    def refresh_audit(self):
        self.audit_text.delete(1.0, tk.END)
        for key, value in self.audit_report.items():
            self.audit_text.insert(tk.END, f"{key}: {value}\n")

    def refine(self):
        prompt = self.chat_area.get("1.0", tk.END).strip()
        if not prompt:
            messagebox.showwarning("Warning", "Enter a prompt to refine.")
            return
        self.status_var.set("Refining with LLM...")
        self.progress_var.set(50)

        def callback(result):
            self.chat_area.insert(tk.END, f"\nRefined: {result}")
            self.progress_var.set(100)
            self.status_var.set("Ready")

        self.llm.query(f"Refine this project idea: {prompt}", callback)

    def generate(self):
        inputs = {
            "name": self.name_entry.get(),
            "type": self.type_var.get(),
            "features": self.features_scale.get(),
        }
        stack = {"frontend": "React", "backend": "FastAPI"}
        yaml = self.template.generate_yaml(inputs, stack)
        self.audit_report = self.auditor.audit_report(yaml, inputs)
        self.refresh_audit()
        self.output_area.insert(tk.END, f"Template generated.\n")
        with open("v2_template.yaml", "w") as f:
            f.write(yaml)

    def build(self):
        try:
            with open("v2_template.yaml", "r") as f:
                yaml_content = f.read()
            self.status_var.set("Building...")
            self.progress_var.set(25)

            def callback(result):
                if result.get("success"):
                    self.auditor.performance_log("build")
                    self.output_area.insert(tk.END, f"Build result: {result}\n")
                    self.progress_var.set(100)
                    self.status_var.set("Build Complete")
                else:
                    messagebox.showerror(
                        "Build Error", result.get("error", "Unknown error")
                    )
                    self.status_var.set("Build Failed")

            self.builder.execute(yaml_content, callback)
        except Exception as e:
            messagebox.showerror("Error", str(e))

    def save_settings(self):
        self.settings.update(
            {
                "llm": self.llm_var.get(),
                "github_token": self.github_entry.get(),
                "gemini_key": self.gemini_entry.get(),
                "auto_save": self.auto_save_var.get(),
            }
        )
        with open("settings.json", "w") as f:
            json.dump(self.settings, f)
        messagebox.showinfo("Settings", "Saved!")

    def load_settings(self):
        try:
            with open("settings.json", "r") as f:
                return json.load(f)
        except:
            return {}

    def save_project(self):
        file_path = filedialog.asksaveasfilename(defaultextension=".json")
        if file_path:
            data = {
                "name": self.name_entry.get(),
                "chat": self.chat_area.get(1.0, tk.END),
            }
            with open(file_path, "w") as f:
                json.dump(data, f)

    def load_project(self):
        file_path = filedialog.askopenfilename(filetypes=[("JSON files", "*.json")])
        if file_path:
            with open(file_path, "r") as f:
                data = json.load(f)
            self.name_entry.delete(0, tk.END)
            self.name_entry.insert(0, data.get("name", ""))
            self.chat_area.delete(1.0, tk.END)
            self.chat_area.insert(tk.END, data.get("chat", ""))

    def run_tests(self):
        print("Running tests...")
        # Inline tests
        assert self.llm.query("test") is not None
        assert self.template.generate_yaml({"name": "test"}, {}) != ""
        print("Tests passed!")

    def build_exe(self):
        print("Building EXE...")
        # Placeholder

    def show_llm_screen(self):
        dialog = tk.Toplevel(self.root)
        dialog.title("LLM Options")
        ttk.Label(dialog, text="Select Provider:").pack()
        provider_var = tk.StringVar(value=self.llm.current)
        ttk.Combobox(
            dialog,
            textvariable=provider_var,
            values=["lm_studio", "huggingface", "ollama", "copilot", "gemini"],
        ).pack()
        ttk.Button(
            dialog,
            text="Apply",
            command=lambda: self.llm.set_provider(provider_var.get()),
        ).pack()

    def show_mcps_screen(self):
        dialog = tk.Toplevel(self.root)
        dialog.title("MCP Options")
        ttk.Label(dialog, text="MCP Server URL:").pack()
        mcp_entry = ttk.Entry(dialog)
        mcp_entry.pack()
        ttk.Button(
            dialog, text="Save", command=lambda: print(f"MCP saved: {mcp_entry.get()}")
        ).pack()

    def show_themes_screen(self):
        dialog = tk.Toplevel(self.root)
        dialog.title("Theme Options")
        ttk.Label(dialog, text="Theme:").pack()
        theme_var = tk.StringVar(value="streetwise")
        ttk.Combobox(
            dialog, textvariable=theme_var, values=["streetwise", "light", "dark"]
        ).pack()
        ttk.Button(
            dialog, text="Apply", command=lambda: print(f"Theme: {theme_var.get()}")
        ).pack()

    def run(self):
        self.root.mainloop()


# EXE Build Function
def build_exe():
    print("Starting EXE build process...")
    try:
        import PyInstaller.__main__

        PyInstaller.__main__.run(
            [
                "improved_perfected_overlay_cheetah_v2.py",
                "--onefile",
                "--name=OverlayCheetahV2",
                "--hidden-import=google.generativeai",
                "--hidden-import=ollama",
                "--hidden-import=github",
                "--hidden-import=transformers",
            ]
        )
        print("EXE built successfully: OverlayCheetahV2.exe")
    except ImportError:
        print("PyInstaller not installed. Run: pip install pyinstaller")
    except Exception as e:
        print(f"Build failed: {e}")


# Testing Suite
def run_tests():
    print("Running tests...")
    try:
        llm = LLMManager()
        response = llm.query("Test prompt")
        assert isinstance(response, str)
        print("✓ LLM test passed")
    except Exception as e:
        print(f"✗ LLM test failed: {e}")

    try:
        template = TemplateEngine()
        yaml = template.generate_yaml(
            {"name": "Test", "features": [1]}, {"stack": "test"}
        )
        assert "task_id" in yaml
        print("✓ Template test passed")
    except Exception as e:
        print(f"✗ Template test failed: {e}")

    try:
        builder = BuildExecutor()
        result = builder.execute("dummy yaml")
        assert result["success"]
        print("✓ Build test passed")
    except Exception as e:
        print(f"✗ Build test failed: {e}")

    print("Tests completed!")


if __name__ == "__main__":
    import sys

    print("Starting OverlayCheetahV2 2.1...")
    if len(sys.argv) > 1:
        if sys.argv[1] == "build":
            build_exe()
        elif sys.argv[1] == "test":
            run_tests()
        else:
            print("Usage: python improved_perfected_overlay_cheetah_v2.py [build|test]")
    else:
        app = OverlayCheetahV2()
        app.run()
