# Overlay Cheetah V2 - Full System
# Vibe-coding app for SaaS projects with LLM integrations, guardrails, and build execution

# Dependencies:
# pip install google-generativeai ollama requests PyGithub transformers tk

# Usage:
# 1. Set environment variables: GITHUB_TOKEN, GEMINI_API_KEY
# 2. Run: python overlay_cheetah_v2_full.py
# 3. For EXE build: python overlay_cheetah_v2_full.py build
# 4. For tests: python overlay_cheetah_v2_full.py test

print("Overlay Cheetah V2 script loaded successfully")

try:
    import json
    import os
    import subprocess
    import tkinter as tk
    from tkinter import messagebox, scrolledtext, ttk

    import google.generativeai as genai  # For Gemini
    import ollama  # For Ollama
    import requests
    from github import Github  # For Copilot (simplified)
    from transformers import pipeline  # For Hugging Face

    print("All imports successful")
except ImportError as e:
    print(f"Import error: {e}")
    print(
        "Please install missing dependencies: pip install google-generativeai ollama requests PyGithub transformers"
    )
    exit(1)
except Exception as e:
    print(f"Unexpected error during imports: {e}")
    exit(1)

print("Proceeding to class definitions...")


class LLMManager:
    def __init__(self):
        print("Initializing LLMManager...")
        self.providers = {
            "lm_studio": {"endpoint": "http://localhost:1234/v1/chat/completions"},
            "huggingface": {"model": "microsoft/DialoGPT-medium"},
            "ollama": {"model": "llama2"},
            "copilot": {"token": os.getenv("GITHUB_TOKEN")},
            "gemini": {"api_key": os.getenv("GEMINI_API_KEY")},
        }
        self.current = "ollama"  # Default

    def set_provider(self, provider):
        self.current = provider

    def query(self, prompt):
        if self.current == "lm_studio":
            response = requests.post(
                self.providers["lm_studio"]["endpoint"],
                json={"messages": [{"role": "user", "content": prompt}]},
            )
            return response.json()["choices"][0]["message"]["content"]
        elif self.current == "huggingface":
            generator = pipeline(
                "text-generation", model=self.providers["huggingface"]["model"]
            )
            return generator(prompt, max_length=50)[0]["generated_text"]
        elif self.current == "ollama":
            response = ollama.chat(
                model=self.providers["ollama"]["model"],
                messages=[{"role": "user", "content": prompt}],
            )
            return response["message"]["content"]
        elif self.current == "copilot":
            g = Github(self.providers["copilot"]["token"])
            # Simplified Copilot simulation
            return f"Copilot suggestion: {prompt}"
        elif self.current == "gemini":
            genai.configure(api_key=self.providers["gemini"]["api_key"])
            model = genai.GenerativeModel("gemini-pro")
            response = model.generate_content(prompt)
            return response.text
        return "LLM not configured"


class TemplateEngine:
    def __init__(self):
        print("Initializing TemplateEngine...")

    def generate_yaml(self, inputs, stack):
        return f"""
task_id: vibe_build_{inputs["name"]}
description: Generated by Overlay Cheetah V2
files:
  - template: main_app.py.j2
    output: app.py
    context:
      app_name: "{inputs["name"]}"
      features: {inputs["features"]}
      stack: {stack}
"""


class BuildExecutor:
    def __init__(self):
        print("Initializing BuildExecutor...")

    def execute(self, yaml_content):
        # Simulate Overlay Cheetah run
        with open("generated_template.yaml", "w") as f:
            f.write(yaml_content)
        # In real: subprocess.run(["python", "overlay_cheetah.py", "generated_template.yaml"])
        return {"success": True, "files": ["app.py", "requirements.txt"]}


class OverlayCheetahV2:
    def __init__(self):
        print("Initializing Overlay Cheetah V2 GUI...")
        self.llm = LLMManager()
        self.template = TemplateEngine()
        self.builder = BuildExecutor()
        print("Creating Tkinter window...")
        self.root = tk.Tk()
        self.root.title("Overlay Cheetah V2")
        self.root.geometry("800x600")
        self.setup_ui()
        print("GUI initialized.")

    def setup_ui(self):
        print("Setting up UI...")
        # LLM Selector
        ttk.Label(self.root, text="LLM Provider:").pack()
        self.llm_var = tk.StringVar(value="ollama")
        ttk.Combobox(
            self.root, textvariable=self.llm_var, values=list(self.llm.providers.keys())
        ).pack()

        # Project Inputs
        ttk.Label(self.root, text="Project Name:").pack()
        self.name_entry = ttk.Entry(self.root)
        self.name_entry.pack()

        ttk.Label(self.root, text="Project Type:").pack()
        self.type_var = tk.StringVar(value="SaaS Web App")
        ttk.Combobox(
            self.root,
            textvariable=self.type_var,
            values=["SaaS Web App", "API Service", "Full-Stack Platform"],
        ).pack()

        ttk.Label(self.root, text="Features (1-10):").pack()
        self.features_scale = tk.Scale(self.root, from_=1, to=10, orient=tk.HORIZONTAL)
        self.features_scale.pack()

        # Chat Area
        ttk.Label(self.root, text="LLM Chat:").pack()
        self.chat_area = scrolledtext.ScrolledText(self.root, height=10)
        self.chat_area.pack()

        # Buttons
        ttk.Button(self.root, text="Refine with LLM", command=self.refine).pack()
        ttk.Button(self.root, text="Generate Template", command=self.generate).pack()
        ttk.Button(self.root, text="Build Project", command=self.build).pack()

        # Output
        self.output_area = scrolledtext.ScrolledText(self.root, height=10)
        self.output_area.pack()

    def refine(self):
        prompt = self.chat_area.get("1.0", tk.END).strip()
        refined = self.llm.query(f"Refine this project idea: {prompt}")
        self.chat_area.insert(tk.END, f"\nRefined: {refined}")

    def generate(self):
        inputs = {
            "name": self.name_entry.get(),
            "type": self.type_var.get(),
            "features": self.features_scale.get(),
        }
        stack = {"frontend": "React", "backend": "FastAPI"}  # Simplified
        yaml = self.template.generate_yaml(inputs, stack)
        with open("v2_template.yaml", "w") as f:
            f.write(yaml)
        self.output_area.insert(tk.END, "Template generated: v2_template.yaml\n")

    def build(self):
        try:
            with open("v2_template.yaml", "r") as f:
                yaml_content = f.read()
            result = self.builder.execute(yaml_content)
            self.output_area.insert(tk.END, f"Build result: {result}\n")
        except Exception as e:
            messagebox.showerror("Error", str(e))

    def run(self):
        self.root.mainloop()


# EXE Build Function
def build_exe():
    """Build the app into an EXE using PyInstaller."""
    print("Starting EXE build process...")
    try:
        import PyInstaller.__main__

        PyInstaller.__main__.run(
            [
                "overlay_cheetah_v2_full.py",
                "--onefile",
                "--name=OverlayCheetahV2",
                "--add-data=llm_manager.py;.",
                "--hidden-import=google.generativeai",
                "--hidden-import=ollama",
                "--hidden-import=github",
                "--hidden-import=transformers",
            ]
        )
        print("EXE built successfully: OverlayCheetahV2.exe")
    except ImportError:
        print("PyInstaller not installed. Run: pip install pyinstaller")
    except Exception as e:
        print(f"Build failed: {e}")


# Testing Suite
def run_tests():
    """Run basic tests for the system."""
    print("Running tests...")

    try:
        # Test LLM Manager
        llm = LLMManager()
        llm.set_provider("ollama")
        response = llm.query("Test prompt")
        assert isinstance(response, str), "LLM query failed"
        print("✓ LLM test passed")
    except Exception as e:
        print(f"✗ LLM test failed: {e}")

    try:
        # Test Template Engine
        template = TemplateEngine()
        yaml = template.generate_yaml(
            {"name": "Test", "features": [1]}, {"stack": "test"}
        )
        assert "task_id" in yaml, "Template generation failed"
        print("✓ Template test passed")
    except Exception as e:
        print(f"✗ Template test failed: {e}")

    try:
        # Test Build Executor
        builder = BuildExecutor()
        result = builder.execute("dummy yaml")
        assert result["success"], "Build execution failed"
        print("✓ Build test passed")
    except Exception as e:
        print(f"✗ Build test failed: {e}")

    print("Tests completed!")


if __name__ == "__main__":
    import sys

    print("Starting Overlay Cheetah V2...")
    if len(sys.argv) > 1:
        if sys.argv[1] == "build":
            print("Building EXE...")
            build_exe()
        elif sys.argv[1] == "test":
            print("Running tests...")
            run_tests()
        else:
            print("Usage: python overlay_cheetah_v2_full.py [build|test]")
    else:
        print("Launching GUI app...")
        app = OverlayCheetahV2()
        app.run()
        print("GUI app closed.")
