# Overlay Cheetah V3 - Lite (Free Version)
# A simplified, free version of OverlayCheetah to get started with vibe-coding
#
# This is the LITE version with limited features. Upgrade to PRO for:
# - Multiple LLM providers (Gemini, Copilot, Ollama, etc.)
# - Advanced audit and security scanning
# - Project save/load functionality
# - Custom themes and MCP integrations
# - Professional build tools and EXE generation
# - Priority support and updates
#
# Dependencies (minimal for lite version):
# pip install pyyaml  # Optional: for parsing generated YAML files

# ============================================================================
# BRANDING INTEGRATION GUIDE
# ============================================================================
# For IDE/GUI implementations, use the branding assets located in:
# - assets/branding/overlay-cheetah-logo.svg (for splash screens, app logo)
# - assets/branding/overlay365-brand.svg (for About dialog, corporate info)
#
# Example Usage:
#
# Splash Screen Integration:
#   LOGO_PATH = os.path.join(os.path.dirname(__file__),
#                            "assets/branding/overlay-cheetah-logo.svg")
#   # Display LOGO_PATH in your splash screen or startup window
#
# About Dialog Integration:
#   BRAND_PATH = os.path.join(os.path.dirname(__file__),
#                             "assets/branding/overlay365-brand.svg")
#   # Display BRAND_PATH in Help > About or company information dialogs
#
# For onboarding wizards, consider showing both:
#   1. overlay-cheetah-logo.svg - Primary product branding
#   2. overlay365-brand.svg - Corporate/company identity
#
# See assets/branding/README.md for complete integration guidelines.
# ============================================================================

import json
import os
import tkinter as tk
from tkinter import messagebox, scrolledtext, ttk
from tkinter.ttk import Progressbar


class TemplateEngine:
    """Basic template generation - limited to simple projects in lite version"""

    def generate_yaml(self, inputs, stack):
        return f"""
task_id: vibe_build_{inputs["name"]}
description: Generated by OverlayCheetah V3 Lite (Free Version)
files:
  - template: main_app.py.j2
    output: app.py
    context:
      app_name: "{inputs["name"]}"
      features: {inputs.get("features", 3)}
      stack: {stack}
note: "Upgrade to PRO for advanced templates and customization!"
"""


class BuildExecutor:
    """Basic build executor - limited output in lite version"""

    def execute(self, yaml_content, callback=None):
        try:
            with open("generated_template_lite.yaml", "w") as f:
                f.write(yaml_content)
            result = {
                "success": True,
                "files": ["app.py"],
                "message": "✓ Basic template generated! Upgrade to PRO for full build automation.",
            }
            if callback:
                callback(result)
        except Exception as e:
            if callback:
                callback({"success": False, "error": str(e)})


class OnboardingWizard:
    """Simple onboarding for first-time users"""

    def __init__(self, root, callback):
        self.root = root
        self.callback = callback
        self.step = 0
        self.data = {}
        self.dialog = tk.Toplevel(root)
        self.dialog.title("Welcome to OverlayCheetah V3 Lite!")
        self.dialog.geometry("600x450")
        self.setup_steps()

    def setup_steps(self):
        self.steps = [
            self.step_welcome,
            self.step_preset,
            self.step_details,
            self.step_upgrade_info,
        ]
        self.next_step()

    def next_step(self):
        if self.step < len(self.steps):
            for widget in self.dialog.winfo_children():
                widget.destroy()
            self.steps[self.step]()
            self.step += 1
        else:
            self.dialog.destroy()
            self.callback(self.data)

    def step_welcome(self):
        ttk.Label(
            self.dialog,
            text="Welcome to OverlayCheetah V3 Lite!",
            font=("Arial", 16, "bold"),
        ).pack(pady=20)
        ttk.Label(
            self.dialog,
            text="🎉 Free version - Build simple SaaS projects quickly!",
            font=("Arial", 12),
        ).pack(pady=10)
        ttk.Label(
            self.dialog,
            text="Let's create your first project together.",
            font=("Arial", 10),
        ).pack(pady=5)
        ttk.Button(self.dialog, text="Get Started", command=self.next_step).pack(
            pady=20
        )

    def step_preset(self):
        ttk.Label(
            self.dialog, text="Choose a starter template:", font=("Arial", 12)
        ).pack(pady=10)
        self.preset_var = tk.StringVar(value="Simple Blog")

        presets = [
            ("Simple Blog", "Basic blog with posts"),
            ("Task List", "Simple todo app"),
            ("Landing Page", "Single page website"),
        ]

        for preset_name, description in presets:
            frame = ttk.Frame(self.dialog)
            frame.pack(pady=5, fill="x", padx=20)
            ttk.Radiobutton(
                frame, text=preset_name, variable=self.preset_var, value=preset_name
            ).pack(side="left")
            ttk.Label(frame, text=f"- {description}", foreground="gray").pack(
                side="left"
            )

        ttk.Label(
            self.dialog,
            text="💡 PRO version includes 15+ advanced templates!",
            foreground="blue",
            font=("Arial", 9, "italic"),
        ).pack(pady=10)

        ttk.Button(self.dialog, text="Next", command=lambda: self.set_preset()).pack(
            pady=20
        )

    def set_preset(self):
        self.data["preset"] = self.preset_var.get()
        self.next_step()

    def step_details(self):
        ttk.Label(self.dialog, text="Project details:", font=("Arial", 12)).pack(
            pady=10
        )

        ttk.Label(self.dialog, text="Project Name:").pack()
        self.name_entry = ttk.Entry(self.dialog, width=40)
        self.name_entry.pack(pady=5)
        self.name_entry.insert(0, "MyFirstProject")

        ttk.Button(self.dialog, text="Next", command=lambda: self.set_details()).pack(
            pady=20
        )

    def set_details(self):
        self.data["name"] = self.name_entry.get()
        self.data["type"] = "Simple SaaS App"
        self.next_step()

    def step_upgrade_info(self):
        ttk.Label(
            self.dialog, text="🚀 Ready to build!", font=("Arial", 14, "bold")
        ).pack(pady=20)

        # Show lite version limitations
        frame = tk.Frame(self.dialog, bg="#ffe6e6", relief="ridge", borderwidth=2)
        frame.pack(pady=10, padx=20, fill="both")

        ttk.Label(
            frame,
            text="⚡ You're using the FREE Lite Version",
            font=("Arial", 11, "bold"),
            background="#ffe6e6",
        ).pack(pady=5)

        ttk.Label(
            frame, text="• Limited to 3 features per project", background="#ffe6e6"
        ).pack(anchor="w", padx=10)
        ttk.Label(frame, text="• Basic templates only", background="#ffe6e6").pack(
            anchor="w", padx=10
        )
        ttk.Label(frame, text="• No LLM integrations", background="#ffe6e6").pack(
            anchor="w", padx=10
        )

        ttk.Button(self.dialog, text="Continue with Lite", command=self.next_step).pack(
            pady=10
        )

        ttk.Button(
            self.dialog, text="🌟 Upgrade to PRO Version", command=self.show_upgrade
        ).pack(pady=5)

    def show_upgrade(self):
        messagebox.showinfo(
            "Upgrade to PRO",
            "OverlayCheetah V3 PRO includes:\n\n"
            "✓ Unlimited features per project\n"
            "✓ 5 LLM providers (Gemini, Copilot, Ollama, etc.)\n"
            "✓ Advanced templates & customization\n"
            "✓ Security scanning & audit tools\n"
            "✓ Project save/load\n"
            "✓ EXE builder\n"
            "✓ Priority support\n\n"
            "Contact: support@overlayapp.com\n"
            "Or visit: https://overlayapp.com/upgrade",
        )


class OverlayCheetahV3Lite:
    """Lite version of OverlayCheetah V3 - Free with limited features"""

    def __init__(self):
        print("Initializing OverlayCheetah V3 Lite GUI...")
        self.template = TemplateEngine()
        self.builder = BuildExecutor()
        self.settings = self.load_settings()

        self.root = tk.Tk()
        self.root.title(
            "OverlayCheetah V3 Lite (FREE Version) - Upgrade to PRO for full features!"
        )
        self.root.geometry("900x700")

        self.setup_styles()
        self.progress_var = tk.DoubleVar()
        self.status_var = tk.StringVar(value="Ready - Free Lite Version")

        # Check for first run
        if not self.settings.get("first_run_done", False):
            self.root.after(100, self.show_onboarding)
        else:
            self.setup_ui()

        print("Lite version GUI initialized.")

    def show_onboarding(self):
        def on_complete(data):
            self.settings["first_run_done"] = True
            self.save_settings()
            self.apply_preset(data)
            self.setup_ui()

        OnboardingWizard(self.root, on_complete)

    def apply_preset(self, data):
        """Apply preset to the main UI"""
        # Store preset data for later use
        self.preset_data = data

    def setup_styles(self):
        """Setup UI theme - simplified for lite version"""
        style = ttk.Style()
        style.theme_use("clam")
        style.configure(
            "TLabel",
            font=("Arial", 10),
            foreground="#333333",
            background="#f0f0f0",
        )
        style.configure(
            "TButton",
            font=("Arial", 9),
            foreground="#0066cc",
            background="#e0e0e0",
        )
        style.configure(
            "Upgrade.TButton",
            font=("Arial", 10, "bold"),
            foreground="#ff6600",
            background="#ffe6cc",
        )
        self.root.configure(bg="#f0f0f0")

    def setup_ui(self):
        """Setup main user interface"""
        # Lite version banner
        banner = tk.Frame(self.root, bg="#ffcc00", height=40)
        banner.pack(side="top", fill="x")
        ttk.Label(
            banner,
            text="⚡ FREE LITE VERSION - Limited Features",
            font=("Arial", 11, "bold"),
            background="#ffcc00",
        ).pack(side="left", padx=10, pady=5)

        upgrade_btn = tk.Button(
            banner,
            text="🌟 UPGRADE TO PRO",
            command=self.show_upgrade_dialog,
            bg="#ff6600",
            fg="white",
            font=("Arial", 10, "bold"),
            relief="raised",
            cursor="hand2",
        )
        upgrade_btn.pack(side="right", padx=10, pady=5)

        # Status bar
        self.status_bar = ttk.Label(
            self.root, textvariable=self.status_var, relief="sunken"
        )
        self.status_bar.pack(side="bottom", fill="x")

        self.progress_bar = Progressbar(
            self.root, variable=self.progress_var, maximum=100
        )
        self.progress_bar.pack(side="bottom", fill="x")

        # Main content area
        main_frame = ttk.Frame(self.root)
        main_frame.pack(fill="both", expand=True, padx=10, pady=10)

        self.setup_main_content(main_frame)

    def setup_main_content(self, frame):
        """Setup main content area"""
        # Project Inputs Section
        input_section = ttk.LabelFrame(
            frame, text="📝 Project Setup (Basic)", padding=10
        )
        input_section.pack(fill="x", pady=5)

        ttk.Label(input_section, text="Project Name:").grid(
            row=0, column=0, sticky="w", pady=5
        )
        self.name_entry = ttk.Entry(input_section, width=40)
        self.name_entry.grid(row=0, column=1, sticky="ew", pady=5)
        self.name_entry.insert(
            0, getattr(self, "preset_data", {}).get("name", "MyProject")
        )

        ttk.Label(input_section, text="Project Type:").grid(
            row=1, column=0, sticky="w", pady=5
        )
        self.type_var = tk.StringVar(value="Simple Web App")
        type_combo = ttk.Combobox(
            input_section,
            textvariable=self.type_var,
            values=["Simple Web App", "Basic API"],
            state="readonly",
            width=37,
        )
        type_combo.grid(row=1, column=1, sticky="ew", pady=5)

        ttk.Label(input_section, text="Features (max 3 in Lite):").grid(
            row=2, column=0, sticky="w", pady=5
        )
        self.features_var = tk.IntVar(value=3)
        features_frame = ttk.Frame(input_section)
        features_frame.grid(row=2, column=1, sticky="ew", pady=5)

        ttk.Label(features_frame, textvariable=self.features_var).pack(side="left")
        ttk.Label(
            features_frame,
            text=" / 3 (Upgrade to PRO for unlimited)",
            foreground="gray",
        ).pack(side="left")

        # Locked features indicator
        locked_section = tk.Frame(frame, bg="#f5f5f5", relief="ridge", borderwidth=1)
        locked_section.pack(fill="x", pady=10)

        ttk.Label(
            locked_section,
            text="🔒 PRO Features (Locked in Lite Version)",
            font=("Arial", 10, "bold"),
            background="#f5f5f5",
        ).pack(pady=5)

        locked_features = [
            "• LLM Integrations (Gemini, Copilot, Ollama)",
            "• Advanced Templates & Customization",
            "• Security Scanning & Audit Tools",
            "• Project Save/Load Functionality",
            "• EXE Builder & Distribution Tools",
            "• Custom Themes & MCP Options",
        ]

        for feature in locked_features:
            ttk.Label(
                locked_section, text=feature, foreground="gray", background="#f5f5f5"
            ).pack(anchor="w", padx=20)

        ttk.Button(
            locked_section,
            text="🌟 Unlock PRO Features",
            command=self.show_upgrade_dialog,
        ).pack(pady=10)

        # Action Buttons
        btn_frame = ttk.Frame(frame)
        btn_frame.pack(fill="x", pady=10)

        ttk.Button(
            btn_frame, text="Generate Basic Template", command=self.generate
        ).pack(side="left", padx=5)

        ttk.Button(btn_frame, text="Build Project (Simple)", command=self.build).pack(
            side="left", padx=5
        )

        ttk.Button(btn_frame, text="Help", command=self.show_help).pack(
            side="right", padx=5
        )

        # Output Area
        output_section = ttk.LabelFrame(frame, text="📄 Output", padding=10)
        output_section.pack(fill="both", expand=True, pady=5)

        self.output_area = scrolledtext.ScrolledText(
            output_section, height=15, wrap=tk.WORD
        )
        self.output_area.pack(fill="both", expand=True)
        self.output_area.insert(
            tk.END,
            "Welcome to OverlayCheetah V3 Lite (FREE Version)!\n\n"
            "Get started by entering your project details above.\n\n"
            "This is the lite version with limited features.\n"
            "Upgrade to PRO for full LLM integrations, advanced templates, and more!\n\n"
            "---\n\n",
        )

    def generate(self):
        """Generate basic template - lite version"""
        name = self.name_entry.get().strip()
        if not name:
            messagebox.showwarning("Warning", "Please enter a project name.")
            return

        inputs = {
            "name": name,
            "type": self.type_var.get(),
            "features": self.features_var.get(),
        }

        stack = {"frontend": "HTML/CSS", "backend": "Python"}
        yaml = self.template.generate_yaml(inputs, stack)

        self.output_area.insert(tk.END, f"\n✓ Template generated for: {name}\n")
        self.output_area.insert(tk.END, f"Type: {inputs['type']}\n")
        self.output_area.insert(
            tk.END, f"Features: {inputs['features']}/3 (Lite limit)\n\n"
        )

        with open("generated_template_lite.yaml", "w") as f:
            f.write(yaml)

        self.output_area.insert(
            tk.END,
            "💡 Tip: Upgrade to PRO for advanced templates with 10x more customization!\n\n",
        )

        self.status_var.set("Template generated - Lite version")

    def build(self):
        """Build project - simplified in lite version"""
        if not os.path.exists("generated_template_lite.yaml"):
            messagebox.showwarning("Warning", "Please generate a template first.")
            return

        try:
            with open("generated_template_lite.yaml", "r") as f:
                yaml_content = f.read()

            self.status_var.set("Building (Basic)...")
            self.progress_var.set(50)

            def callback(result):
                if result.get("success"):
                    self.output_area.insert(
                        tk.END, f"\n✓ {result.get('message', 'Build complete!')}\n"
                    )
                    self.output_area.insert(
                        tk.END, f"Files: {', '.join(result.get('files', []))}\n\n"
                    )
                    self.progress_var.set(100)
                    self.status_var.set("Build Complete (Lite)")

                    # Remind about PRO features
                    self.output_area.insert(
                        tk.END,
                        "🌟 PRO version includes: Full build automation, testing, and deployment!\n\n",
                    )
                else:
                    messagebox.showerror(
                        "Build Error", result.get("error", "Unknown error")
                    )
                    self.status_var.set("Build Failed")

            self.builder.execute(yaml_content, callback)

        except Exception as e:
            messagebox.showerror("Error", str(e))
            self.status_var.set("Error")

    def show_upgrade_dialog(self):
        """Show upgrade information dialog"""
        dialog = tk.Toplevel(self.root)
        dialog.title("Upgrade to OverlayCheetah V3 PRO")
        dialog.geometry("600x550")
        dialog.configure(bg="white")

        # Header
        header = tk.Frame(dialog, bg="#0066cc", height=80)
        header.pack(fill="x")
        tk.Label(
            header,
            text="🚀 Upgrade to PRO",
            font=("Arial", 20, "bold"),
            bg="#0066cc",
            fg="white",
        ).pack(pady=20)

        # Content
        content = tk.Frame(dialog, bg="white")
        content.pack(fill="both", expand=True, padx=30, pady=20)

        tk.Label(
            content,
            text="Unlock the full power of OverlayCheetah V3!",
            font=("Arial", 14),
            bg="white",
        ).pack(pady=10)

        features = [
            "✓ 5 LLM Providers (Gemini, Copilot, Ollama, LM Studio, Hugging Face)",
            "✓ Unlimited Features per Project",
            "✓ 15+ Professional Templates",
            "✓ Security Scanning & Audit Tools",
            "✓ Project Save/Load & Version Control",
            "✓ EXE Builder & Distribution",
            "✓ Custom Themes & Branding",
            "✓ MCP Server Integration",
            "✓ Priority Support & Updates",
            "✓ Commercial License Included",
        ]

        for feature in features:
            tk.Label(
                content, text=feature, font=("Arial", 11), bg="white", anchor="w"
            ).pack(fill="x", pady=3)

        # Pricing
        pricing_frame = tk.Frame(dialog, bg="#f0f0f0", relief="ridge", borderwidth=2)
        pricing_frame.pack(fill="x", padx=30, pady=10)

        tk.Label(
            pricing_frame,
            text="Special Launch Price: $49 (Regular $99)",
            font=("Arial", 14, "bold"),
            bg="#f0f0f0",
            fg="#cc0000",
        ).pack(pady=10)

        # Action buttons
        btn_frame = tk.Frame(dialog, bg="white")
        btn_frame.pack(pady=15)

        tk.Button(
            btn_frame,
            text="🛒 Purchase PRO Version",
            command=lambda: self.open_purchase_link(),
            bg="#ff6600",
            fg="white",
            font=("Arial", 12, "bold"),
            padx=20,
            pady=10,
            cursor="hand2",
        ).pack(side="left", padx=5)

        tk.Button(
            btn_frame,
            text="Learn More",
            command=lambda: self.open_website(),
            bg="#0066cc",
            fg="white",
            font=("Arial", 12),
            padx=20,
            pady=10,
            cursor="hand2",
        ).pack(side="left", padx=5)

        tk.Button(
            btn_frame,
            text="Maybe Later",
            command=dialog.destroy,
            bg="#cccccc",
            font=("Arial", 10),
            padx=15,
            pady=10,
        ).pack(side="left", padx=5)

    def open_purchase_link(self):
        """Open purchase page"""
        messagebox.showinfo(
            "Purchase PRO",
            "Visit our website to purchase:\n\n"
            "https://overlayapp.com/purchase\n\n"
            "Or contact sales@overlayapp.com",
        )

    def open_website(self):
        """Open product website"""
        messagebox.showinfo(
            "Learn More",
            "Learn more about OverlayCheetah V3 PRO:\n\n"
            "https://overlayapp.com/cheetah-pro\n\n"
            "Features, demos, and testimonials available online!",
        )

    def show_help(self):
        """Show help dialog"""
        messagebox.showinfo(
            "Help - Lite Version",
            "OverlayCheetah V3 Lite - Quick Start:\n\n"
            "1. Enter your project name\n"
            "2. Choose project type\n"
            "3. Click 'Generate Basic Template'\n"
            "4. Click 'Build Project (Simple)'\n\n"
            "Note: Lite version has limited features.\n"
            "Upgrade to PRO for full capabilities!\n\n"
            "Support: support@overlayapp.com",
        )

    def save_settings(self):
        """Save basic settings"""
        with open("settings_lite.json", "w") as f:
            json.dump(self.settings, f)

    def load_settings(self):
        """Load basic settings"""
        try:
            with open("settings_lite.json", "r") as f:
                return json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            return {}

    def run(self):
        """Run the application"""
        self.root.mainloop()


if __name__ == "__main__":
    import sys

    print("Starting OverlayCheetah V3 Lite (FREE Version)...")
    print("Upgrade to PRO for full features: https://overlayapp.com/upgrade")

    app = OverlayCheetahV3Lite()
    app.run()
