#!/usr/bin/env python3
"""
Cheetah Server — FastAPI bridge exposing Cheetah V3 Pro+ (agent, audit,
Recourse) over HTTP.

This is the server Deepseek Harness `cheetah.ts` expects at CHEETAH_URL
(default http://127.0.0.1:4120) with `GET /health`, `POST /generate`,
`POST /build`. Those three endpoints are implemented compatibly; everything
else is new in v4:

- POST /agent/read, /agent/search, /agent/plan  (repo-aware coding agent)
- POST /audit                                    (security + correctness)
- POST /recourse/verify, /recourse/heal, /recourse/promote, GET /recourse/status

Run:  python cheetah_server.py            (serves :4120)
      python cheetah_server.py --port 4120
Requires: fastapi, uvicorn (both in requirements.txt).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

try:
    from fastapi import FastAPI
    from pydantic import BaseModel, Field
    import uvicorn
    FASTAPI_AVAILABLE = True
except ImportError:
    FASTAPI_AVAILABLE = False

from cheetah_agent import Workspace, run_coding_task
from cheetah_audit import audit_files, audit_workspace
from recourse_bridge import (
    DEFAULT_RECOURSE_URL, PromotionLedger, RecourseClient,
    full_promotion_pipeline,
)

VERSION = "4.0.0-server"
DEFAULT_PORT = 4120

if FASTAPI_AVAILABLE:
    app = FastAPI(title="Overlay Cheetah V3 Pro+",
                  version=VERSION)

    # -- compat models (cheetah.ts) --------------------------------------
    class GenerateRequest(BaseModel):
        name: str = "axiom-build"
        project_type: str = "Full-Stack Platform"
        description: str = ""
        enrich: bool = False

    class BuildRequest(BaseModel):
        yaml_content: str
        target_dir: str = "out"

    # -- agent / audit / recourse models -----------------------------------
    class AgentReadRequest(BaseModel):
        root: str
        path: str

    class AgentSearchRequest(BaseModel):
        root: str
        pattern: str
        glob: str = "**/*.py"
        limit: int = 100

    class AgentPlanRequest(BaseModel):
        root: str
        plan: List[Dict[str, Any]]

    class AuditRequest(BaseModel):
        files: Optional[Dict[str, str]] = None
        root: Optional[str] = None
        glob: str = "**/*.py"
        strict: bool = True
        run_tests: bool = False

    class VerifyRequest(BaseModel):
        sourceCode: str
        testSuiteCode: str = ""
        domain: str = "coding"

    class HealRequest(BaseModel):
        toolName: str
        brokenCode: str
        faultHint: str = ""

    class PromoteRequest(BaseModel):
        toolName: str
        sourceCode: str
        testSuiteCode: str = ""

    # -- compat endpoints ----------------------------------------------------
    @app.get("/health")
    def health() -> Dict[str, Any]:
        recourse = RecourseClient().reachable()
        return {"status": "ok", "service": "cheetah-v3-pro+",
                "version": VERSION,
                "recourse_online": recourse.get("online", False),
                "recourse_url": DEFAULT_RECOURSE_URL}

    @app.post("/generate")
    def generate(req: GenerateRequest) -> Dict[str, Any]:
        safe = "".join(c if c.isalnum() or c in ("-", "_", " ") else ""
                       for c in req.name).strip()[:40] or "axiom-build"
        task_id = safe.lower().replace(" ", "_")
        yaml_text = (
            f"# Generated by Cheetah V3 Pro+ {VERSION}\n"
            f"task_id: vibe_build_{task_id}\n"
            f"project_type: \"{req.project_type}\"\n"
            f"description: |\n  {req.description[:2000]}\n"
            f"files: []\nbuild:\n  validate: true\n  profile: true\n"
        )
        out_dir = Path(__file__).resolve().parent / "out"
        out_dir.mkdir(exist_ok=True)
        saved = out_dir / f"generated_{task_id}.yaml"
        saved.write_text(yaml_text, encoding="utf-8")
        return {"yaml": yaml_text, "saved_to": str(saved)}

    @app.post("/build")
    def build(req: BuildRequest) -> Dict[str, Any]:
        import yaml as _yaml
        try:
            spec = _yaml.safe_load(req.yaml_content)
        except Exception as exc:
            return {"ok": False, "error": f"YAML validation failed: {exc}",
                    "files": []}
        out_dir = (Path(__file__).resolve().parent / req.target_dir)
        try:
            out_dir.resolve().relative_to(Path(__file__).resolve().parent.resolve())
        except ValueError:
            return {"ok": False, "error": "target_dir escapes cheetah root",
                    "files": []}
        out_dir.mkdir(parents=True, exist_ok=True)
        written: List[str] = []
        for item in (spec.get("files") or [] if isinstance(spec, dict) else []):
            rel = str(item.get("output", "")).lstrip("/\\")
            if not rel or ".." in rel:
                continue
            dest = (out_dir / rel)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(item.get("rendered", "") or "", encoding="utf-8")
            written.append(str(dest))
        if not written:
            fallback = out_dir / "generated_template_pro.yaml"
            fallback.write_text(req.yaml_content, encoding="utf-8")
            written.append(str(fallback))
        return {"ok": True, "files": written}

    # -- agent -----------------------------------------------------------------
    @app.post("/agent/read")
    def agent_read(req: AgentReadRequest) -> Dict[str, Any]:
        return Workspace(Path(req.root)).read_file(req.path)

    @app.post("/agent/search")
    def agent_search(req: AgentSearchRequest) -> Dict[str, Any]:
        return Workspace(Path(req.root)).search(req.pattern, req.glob,
                                                req.limit)

    @app.post("/agent/plan")
    def agent_plan(req: AgentPlanRequest) -> Dict[str, Any]:
        return run_coding_task(req.root, req.plan)

    # -- audit -------------------------------------------------------------------
    @app.post("/audit")
    def audit(req: AuditRequest) -> Dict[str, Any]:
        if req.files:
            return audit_files(req.files, strict=req.strict)
        if req.root:
            return audit_workspace(req.root, glob=req.glob,
                                   strict=req.strict,
                                   run_tests=req.run_tests)
        return {"ok": False, "passed": False,
                "error": "provide files{} or root"}

    # -- recourse ------------------------------------------------------------------
    @app.get("/recourse/status")
    def recourse_status() -> Dict[str, Any]:
        client = RecourseClient()
        reach = client.reachable()
        local_tools = PromotionLedger()._load().get("tools", {})
        return {"recourse": reach, "local_promotions": len(local_tools)}

    @app.post("/recourse/verify")
    def recourse_verify(req: VerifyRequest) -> Dict[str, Any]:
        client = RecourseClient()
        remote = client.verify(req.sourceCode, req.testSuiteCode,
                               domain=req.domain)
        local = audit_files({"candidate.js": req.sourceCode})
        return {"remote": remote, "local_audit": local}

    @app.post("/recourse/heal")
    def recourse_heal(req: HealRequest) -> Dict[str, Any]:
        return RecourseClient().heal(req.toolName, req.brokenCode,
                                     req.faultHint)

    @app.post("/recourse/promote")
    def recourse_promote(req: PromoteRequest) -> Dict[str, Any]:
        audit_report = audit_files({f"{req.toolName}": req.sourceCode})
        return full_promotion_pipeline(req.toolName, req.sourceCode,
                                       req.testSuiteCode, audit_report)


def main() -> int:
    parser = argparse.ArgumentParser(description="Cheetah V3 Pro+ server")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--host", default="127.0.0.1")
    args = parser.parse_args()
    if not FASTAPI_AVAILABLE:
        print("ERROR: fastapi/uvicorn not installed. Run: "
              "pip install fastapi uvicorn", file=sys.stderr)
        return 2
    uvicorn.run(app, host=args.host, port=args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
