// Typed accessor over the IDS export generated by initiatives/export-web.mjs.
// Never edit initiatives.generated.json by hand — run `node initiatives/export-web.mjs`.
import raw from './initiatives.generated.json';

export interface HardwareInterfaces {
  telemetryTopic?: string;
  controlTopic?: string;
  deviceTypes?: string[];
  sensors?: string[];
  actuators?: string[];
}

export interface HardwareTier {
  name: string;
  audience: string;
  mode: 'community' | 'commercial' | 'internal';
  unit?: string;
  topology?: string;
  bom?: Array<{ part: string; qty: number; unitUsd?: number | null; sourcing?: string; supplier?: string | null; source?: string }>;
  interfaces?: HardwareInterfaces;
  power?: string | null;
  powerBudget?: string | null;
  buildHours?: number | null;
  sla?: string | null;
  verification?: string[];
  status: 'draft' | 'verified';
  missing?: string[];
}

export interface InitiativeSpec {
  code: string;
  id: string;
  name: string;
  type: string;
  stage: string;
  phase: number;
  tracks: string[];
  software: { capabilities: Array<{ id: string; name: string; api?: string | null; status: string; evidence?: string }> };
  hardware: { individual: HardwareTier; enterprise: HardwareTier };
  founding: {
    status: string;
    parent: string;
    division: string;
    ventureName: string;
    structure: string;
    licenses: string[];
    capitalAsk: string;
    offtake: string | null;
    compliance: string[];
    readiness: { hardwarePilot: boolean; partnerLoi: boolean; unitEconomics: boolean };
  };
  derived: { readinessScore: number; gapCount: number };
}

export const initiativeSpecs = raw as unknown as Record<string, InitiativeSpec>;

export function getInitiativeSpec(code: string): InitiativeSpec | undefined {
  return initiativeSpecs[code];
}
